const recipes = [
  {
    _id: "1",
    name: "Spaghetti Aglio Olio e Peperoncino",
    image: "/images/garlic-oil-spaghetti.jpeg",
    category: "Pasta",
    ingredients: "linguine",
  },
  {
    _id: "2",
    name: "Bolognese ragù with pappardelle",
    image: "/images/ragu.jpeg",
    category: "Pasta",
    ingredients: "papperdelle",
  },
  {
    _id: "3",
    name: "Pork meatballs with anchovies",
    image: "/images/pork-anchovie.jpeg",
    category: "Mediterranean",
    ingredients: "pork",
  },
  {
    _id: "4",
    name: "Taiwanese Seabass",
    image: "/images/taiwanese-seabass.jpeg",
    category: "Asian",
    ingredients: "Seabass",
  },
  {
    _id: "5",
    name: "Katsu Curry",
    image: "/images/katsu-curry.jpeg",
    category: "Asian",
    ingredients: "Chicken",
  },
  {
    _id: "6",
    name: "Chicken with Lemon",
    image: "/images/chicken-lemon.jpeg",
    category: "Mediterranean",
    ingredients: "chicken",
  },
  {
    _id: "7",
    name: "Coconut Chickpeas",
    image: "/images/chickpeas-coconut.jpeg",
    category: "Mediterranean",
    ingredients: "chickpeas",
  },
  {
    _id: "6",
    name: "Chicken with Lemon",
    image: "/images/chicken-lemon.jpeg",
    category: "Mediterranean",
    ingredients: "chicken",
  },
  {
    _id: "7",
    name: "Coconut Chickpeas",
    image: "/images/chickpeas-coconut.jpeg",
    category: "Mediterranean",
    ingredients: "chickpeas",
  },
  {
    _id: "6",
    name: "Chicken with Lemon",
    image: "/images/chicken-lemon.jpeg",
    category: "Mediterranean",
    ingredients: "chicken",
  },
  {
    _id: "7",
    name: "Coconut Chickpeas",
    image: "/images/chickpeas-coconut.jpeg",
    category: "Mediterranean",
    ingredients: "chickpeas",
  },
  {
    _id: "6",
    name: "Chicken with Lemon",
    image: "/images/chicken-lemon.jpeg",
    category: "Mediterranean",
    ingredients: "chicken",
  },
  {
    _id: "7",
    name: "Coconut Chickpeas",
    image: "/images/chickpeas-coconut.jpeg",
    category: "Mediterranean",
    ingredients: "chickpeas",
  },
  {
    _id: "6",
    name: "Chicken with Lemon",
    image: "/images/chicken-lemon.jpeg",
    category: "Mediterranean",
    ingredients: "chicken",
  },
  {
    _id: "7",
    name: "Coconut Chickpeas",
    image: "/images/chickpeas-coconut.jpeg",
    category: "Mediterranean",
    ingredients: "chickpeas",
  },
];

export default recipes;
